### PR TITLE
Updated to current savings format

### PR DESCRIPTION
**Pull request by gpz500**
Hello,
it seems that Fineco has slightly changed the report file for the account movements: in order to import my savings report, I have had to change the plugin as in this pull request.

I don't know if these differences are specific to me or are generalized... hope to be useful to someone!

### CODE REVIEW

**Review by shatteringlass — APPROVED** [review]

**Comment by frankIT** [comment]
Thank you for the pull.
I did verify that the saving header changed, so i merged it, but actually the saving statement i downloaded mismatches because of an empty string found in the xslx heading row:
```
expected: ['Data', 'Entrate', 'Uscite', 'Descrizione', 'Descrizione_Completa', 'Stato']
current:  ['Data', 'Entrate', 'Uscite', 'Descrizione', 'Descrizione_Completa', 'Stato', '']
```
I should investigate why that empty string gets appended to the row in the first place, but havn't you bumped into this as well?

**Comment by nicosemp** [comment]
I believe that column G (index 6) is wider than it should, even though it's completely empty. This makes `sheet.row_values` read that column too, as if it contained data inside.

image

I patched this by adding a block after the `first_col_empty` loop:
```python
last_col_empty = True
  for cell in sheet.col_values(6): # This hardcoded 6 could cause issues for other file variants
      if cell != "":
          last_col_empty = False
          break
```

NOTE: add a `break` inside the first loop too, no need to loop the whole thing once you know it's `False`.

And changing the `sheet.row_values` inside the `for rowidx in range(sheet.nrows):` loop to this:

```python
start_colx = 0
if first_col_empty:
    start_colx = 1
if last_col_empty:
    end_colx = 6
row = sheet.row_values(rowidx, start_colx, end_colx)
```

However this works for me with today's export, but maybe there are versions that break because they have MoneyMap columns for example? The hardcoded `6` is not ideal.

**Comment by frankIT** [comment]
I'm not too sure what "wider" means technically, and still looks like an unwanted parsing behavior from xlrd to me. But i did notice as well that that last column should be handled as "optional", rather then hardcode it in the header template. 

If you just open the statement file with libreoffice then save it, that last blank column disappear, despite the spreadsheet looks the exact same.

I still have to test the parsing result, but if that last blank column never contains any data, it just need to pass the `validate()` method, while the parsing logic in `parse()` should not be affected.
On the contrary, that's needed with the cards statement file (the one handled with `first_col_empty` flag), which have shifted data because the blank column is the leading one.

Still have to test it properly, but that's basically the reason why i was implementing [this fix](https://github.com/frankIT/ofxstatement-fineco/commit/845d51c2898044a39b2259a9e1245a086bc7ad1c) in `validate()` only.

Let's follow up on #18 if you wish to test it. cheers

**Comment by gpz500** [comment]
> Thank you for the pull. I did verify that the saving header changed, so i merged it, but actually the saving statement i downloaded mismatches because of an empty string found in the xslx heading row:
> 
> ```
> expected: ['Data', 'Entrate', 'Uscite', 'Descrizione', 'Descrizione_Completa', 'Stato']
> current:  ['Data', 'Entrate', 'Uscite', 'Descrizione', 'Descrizione_Completa', 'Stato', '']
> ```
> 
> I should investigate why that empty string gets appended to the row in the first place, but havn't you bumped into this as well?

The "G empty column" is a fairly recent news, while my pull request dates back a year and a half ago. When it came out, I was satisfied to open and save the file to make it processable 😀

**Comment by frankIT** [comment]
> > Thank you for the pull. I did verify that the saving header changed, so i merged it, but actually the saving statement i downloaded mismatches because of an empty string found in the xslx heading row:
> > ```
> > expected: ['Data', 'Entrate', 'Uscite', 'Descrizione', 'Descrizione_Completa', 'Stato']
> > current:  ['Data', 'Entrate', 'Uscite', 'Descrizione', 'Descrizione_Completa', 'Stato', '']
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I should investigate why that empty string gets appended to the row in the first place, but havn't you bumped into this as well?
> 
> The "G empty column" is a fairly recent news, while my pull request dates back a year and a half ago. When it came out, I was satisfied to open and save the file to make it processable 😀

You're right, I've been woken up from your recent b6da7d5ee648627106d79752f522828dc4f7de00, and  noticed how old was this pull only after having answered. Sry for coming back to this so late. Have been mantaining this repo quite discontinuously, but better now then never right? :rofl: ..glad you still managed to parse your statement when you needed it. I'll follow up about the new G column in the dedicated PR #18

**Comment by nicosemp** [comment]
I closed that PR as the current staging code is parsing without issues 👌 
I still suggest you add a `break` [after line 84](https://github.com/frankIT/ofxstatement-fineco/blob/staging/src/ofxstatement_fineco/plugin.py#L84): you are looking for at least one non-empty cell, so as soon as you find one `first_col_empty` is `False` and you don't need to look anymore.

**Pull request merged**
